# backend/app/services/compliance_service.py
from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..domain.compliance.hqs import summarize_items, top_fix_candidates
from ..models import (
    AuditEvent,
    Inspection,
    Property,
    PropertyChecklistItem,
    RehabTask,
    WorkflowEvent,
)


def _latest_inspection_passed(db: Session, *, property_id: int) -> bool:
    latest = db.scalar(
        select(Inspection).where(Inspection.property_id == property_id).order_by(Inspection.id.desc()).limit(1)
    )
    return bool(latest.passed) if latest else False


def _ensure_rehab_task(
    db: Session,
    *,
    org_id: int,
    property_id: int,
    title: str,
    category: str,
    severity: int,
    notes: str,
) -> bool:
    """
    Create a rehab task only if not already present.
    Uniqueness is enforced by uq_rehab_tasks_org_property_title in models.
    Returns True if created, False if already exists.
    """
    existing = db.scalar(
        select(RehabTask).where(
            RehabTask.org_id == org_id,
            RehabTask.property_id == property_id,
            RehabTask.title == title,
        )
    )
    if existing:
        return False

    now = datetime.utcnow()
    db.add(
        RehabTask(
            org_id=org_id,
            property_id=property_id,
            title=title,
            category=category or "compliance",
            status="open",
            priority="high" if severity >= 4 else "med",
            estimated_cost=None,
            actual_cost=None,
            notes=notes,
            created_at=now,
            updated_at=now,
        )
    )
    return True


def run_hqs(
    db: Session,
    *,
    org_id: int,
    actor_user_id: int,
    actor_email: str,
    property_id: int,
    auto_create_rehab_tasks: bool = True,
    max_tasks_created: int = 25,
) -> dict[str, Any]:
    """
    Deterministic compliance run:
      - Reads checklist item state from PropertyChecklistItem
      - Computes summary + fix candidates
      - Optionally creates rehab tasks (idempotent)
      - Emits workflow events + audit

    This is the “Phase 3 becomes real” loop.
    """
    prop = db.scalar(select(Property).where(Property.id == property_id, Property.org_id == org_id))
    if not prop:
        raise ValueError("property not found")

    items = db.scalars(
        select(PropertyChecklistItem).where(
            PropertyChecklistItem.org_id == org_id,
            PropertyChecklistItem.property_id == property_id,
        )
    ).all()

    latest_passed = _latest_inspection_passed(db, property_id=property_id)

    summary = summarize_items(items, latest_inspection_passed=latest_passed)
    fix_next = top_fix_candidates(items, limit=15)

    created = 0
    if auto_create_rehab_tasks:
        for row in fix_next:
            if created >= max_tasks_created:
                break

            title = f"HQS: {row['item_code']} — {row['description'][:80]}".strip()
            notes = (
                f"Generated by HQS run.\n"
                f"Item: {row['item_code']}\n"
                f"Category: {row['category']}\n"
                f"Severity: {row['severity']}\n"
                f"Status: {row['status']}\n"
            )

            if _ensure_rehab_task(
                db,
                org_id=org_id,
                property_id=property_id,
                title=title,
                category=row["category"],
                severity=int(row["severity"]),
                notes=notes,
            ):
                created += 1

    now = datetime.utcnow()

    payload = {
        "property_id": property_id,
        "summary": {
            "total": summary.total,
            "done": summary.done,
            "failed": summary.failed,
            "pct_done": summary.pct_done,
            "latest_inspection_passed": latest_passed,
            "passed": summary.passed,
        },
        "fix_next": fix_next,
        "rehab_tasks_created": created,
    }

    db.add(
        WorkflowEvent(
            org_id=org_id,
            property_id=property_id,
            actor_user_id=actor_user_id,
            event_type="hqs_run",
            payload_json=json.dumps(payload),
            created_at=now,
        )
    )

    db.add(
        AuditEvent(
            org_id=org_id,
            actor_user_id=actor_user_id,
            action="hqs_run",
            entity_type="property",
            entity_id=str(property_id),
            before_json=None,
            after_json=json.dumps(payload),
            created_at=now,
        )
    )

    db.commit()
    return payload
